/* ------------------------------------------------------------------ */
/* BAZA SŁÓWEK — pogrupowana wg kategorii tematycznych i poziomów CEFR  */
/* Poziomy (A1/A2/B1/B2) są przybliżone (heurystyczne), nie certyfikowane. */
/* ------------------------------------------------------------------ */

export const TOPICS = [
  { id: 'dom', name: 'Dom' },
  { id: 'kuchnia', name: 'Kuchnia i gotowanie' },
  { id: 'owoce', name: 'Owoce' },
  { id: 'warzywa', name: 'Warzywa' },
  { id: 'jedzenie', name: 'Jedzenie i posiłki' },
  { id: 'napoje', name: 'Napoje' },
  { id: 'rodzina', name: 'Rodzina' },
  { id: 'cialo', name: 'Ciało człowieka' },
  { id: 'zdrowie', name: 'Zdrowie i choroby' },
  { id: 'ubrania', name: 'Ubrania i akcesoria' },
  { id: 'kolory', name: 'Kolory' },
  { id: 'ksztalty', name: 'Kształty' },
  { id: 'liczby', name: 'Liczby' },
  { id: 'czas', name: 'Czas, dni i miesiące' },
  { id: 'pogoda', name: 'Pogoda' },
  { id: 'zwierzeta', name: 'Zwierzęta' },
  { id: 'przyroda', name: 'Przyroda' },
  { id: 'transport', name: 'Transport' },
  { id: 'podroze', name: 'Podróże i wakacje' },
  { id: 'miasto', name: 'Miasto i budynki' },
  { id: 'szkola', name: 'Szkoła i edukacja' },
  { id: 'biznes', name: 'Praca i biznes' },
  { id: 'technologia', name: 'Technologia' },
  { id: 'sport', name: 'Sport' },
  { id: 'uczucia', name: 'Uczucia i emocje' },
  { id: 'charakter', name: 'Charakter' },
  { id: 'czasowniki', name: 'Czasowniki podstawowe' },
  { id: 'przymiotniki', name: 'Przymiotniki podstawowe' },
  { id: 'zakupy', name: 'Zakupy i pieniądze' },
  { id: 'hobby', name: 'Hobby i czas wolny' },
  { id: 'wlasne', name: 'Moje słówka' },
];

// [angielski, polski, poziom]
export const WORDS_RAW = {
  dom: [
    ['house', 'dom', 'A1'], ['home', 'dom (rodzinny)', 'A1'], ['room', 'pokój', 'A1'],
    ['door', 'drzwi', 'A1'], ['window', 'okno', 'A1'], ['table', 'stół', 'A1'],
    ['chair', 'krzesło', 'A1'], ['bed', 'łóżko', 'A1'], ['kitchen', 'kuchnia', 'A1'],
    ['bathroom', 'łazienka', 'A1'], ['wall', 'ściana', 'A1'], ['floor', 'podłoga', 'A1'],
    ['living room', 'salon', 'A2'], ['bedroom', 'sypialnia', 'A2'], ['ceiling', 'sufit', 'A2'],
    ['roof', 'dach', 'A2'], ['garden', 'ogród', 'A2'], ['lamp', 'lampa', 'A2'],
    ['sofa', 'sofa', 'A2'], ['mirror', 'lustro', 'A2'], ['shelf', 'półka', 'A2'],
    ['wardrobe', 'szafa', 'A2'], ['drawer', 'szuflada', 'A2'], ['curtain', 'zasłona', 'A2'],
    ['carpet', 'dywan', 'A2'], ['key', 'klucz', 'A2'], ['garage', 'garaż', 'A2'],
    ['staircase', 'klatka schodowa', 'B1'], ['corridor', 'korytarz', 'B1'], ['attic', 'strych', 'B1'],
    ['basement', 'piwnica', 'B1'], ['balcony', 'balkon', 'B1'], ['fence', 'płot', 'B1'],
    ['gate', 'brama', 'B1'], ['doorbell', 'dzwonek do drzwi', 'B1'], ['chimney', 'komin', 'B1'],
    ['furniture', 'meble', 'B1'], ['cushion', 'poduszka ozdobna', 'B1'], ['blanket', 'koc', 'B1'],
    ['pillow', 'poduszka', 'B1'], ['rug', 'dywanik', 'B1'], ['skirting board', 'listwa przypodłogowa', 'B2'],
    ['mantelpiece', 'gzyms kominka', 'B2'], ['veranda', 'weranda', 'B2'], ['hallway', 'przedpokój', 'B2'],
    ['landlord', 'wynajmujący', 'B2'],
  ],
  kuchnia: [
    ['plate', 'talerz', 'A1'], ['glass', 'szklanka', 'A1'], ['cup', 'kubek', 'A1'],
    ['spoon', 'łyżka', 'A1'], ['fork', 'widelec', 'A1'], ['knife', 'nóż', 'A1'],
    ['pot', 'garnek', 'A2'], ['pan', 'patelnia', 'A2'], ['oven', 'piekarnik', 'A2'],
    ['fridge', 'lodówka', 'A2'], ['sink', 'zlew', 'A2'], ['kettle', 'czajnik', 'A2'],
    ['to cook', 'gotować', 'A2'], ['to boil', 'gotować (we wrzątku)', 'A2'], ['to fry', 'smażyć', 'A2'],
    ['to bake', 'piec', 'A2'], ['to cut', 'kroić', 'A2'], ['to mix', 'mieszać', 'A2'],
    ['recipe', 'przepis', 'B1'], ['ingredient', 'składnik', 'B1'], ['dish', 'danie', 'B1'],
    ['bowl', 'miska', 'B1'], ['tray', 'taca', 'B1'], ['cutting board', 'deska do krojenia', 'B1'],
    ['grater', 'tarka', 'B1'], ['whisk', 'trzepaczka', 'B1'], ['microwave', 'mikrofalówka', 'B1'],
    ['dishwasher', 'zmywarka', 'B1'], ['to peel', 'obierać', 'B1'], ['to grill', 'grillować', 'B1'],
    ['to season', 'przyprawiać', 'B2'], ['to simmer', 'gotować na wolnym ogniu', 'B2'],
    ['to marinate', 'marynować', 'B2'], ['saucepan', 'rondel', 'B2'], ['colander', 'durszlak', 'B2'],
  ],
  owoce: [
    ['apple', 'jabłko', 'A1'], ['banana', 'banan', 'A1'], ['orange', 'pomarańcza', 'A1'],
    ['lemon', 'cytryna', 'A1'], ['pear', 'gruszka', 'A1'], ['grape', 'winogrono', 'A2'],
    ['strawberry', 'truskawka', 'A2'], ['cherry', 'wiśnia', 'A2'], ['peach', 'brzoskwinia', 'A2'],
    ['plum', 'śliwka', 'A2'], ['watermelon', 'arbuz', 'A2'], ['pineapple', 'ananas', 'A2'],
    ['raspberry', 'malina', 'B1'], ['blueberry', 'jagoda', 'B1'], ['kiwi', 'kiwi', 'B1'],
    ['mango', 'mango', 'B1'], ['melon', 'melon', 'B1'], ['apricot', 'morela', 'B1'],
    ['fig', 'figa', 'B1'], ['coconut', 'kokos', 'B1'], ['blackberry', 'jeżyna', 'B2'],
    ['gooseberry', 'agrest', 'B2'], ['pomegranate', 'granat', 'B2'], ['grapefruit', 'grejpfrut', 'B2'],
    ['currant', 'porzeczka', 'B2'],
  ],
  warzywa: [
    ['potato', 'ziemniak', 'A1'], ['tomato', 'pomidor', 'A1'], ['carrot', 'marchewka', 'A1'],
    ['onion', 'cebula', 'A1'], ['cucumber', 'ogórek', 'A1'], ['cabbage', 'kapusta', 'A2'],
    ['pepper', 'papryka', 'A2'], ['lettuce', 'sałata', 'A2'], ['garlic', 'czosnek', 'A2'],
    ['broccoli', 'brokuł', 'A2'], ['spinach', 'szpinak', 'A2'], ['mushroom', 'grzyb', 'A2'],
    ['pea', 'groszek', 'A2'], ['corn', 'kukurydza', 'A2'], ['pumpkin', 'dynia', 'B1'],
    ['beetroot', 'burak', 'B1'], ['radish', 'rzodkiewka', 'B1'], ['cauliflower', 'kalafior', 'B1'],
    ['zucchini', 'cukinia', 'B1'], ['leek', 'por', 'B1'], ['celery', 'seler naciowy', 'B1'],
    ['asparagus', 'szparagi', 'B2'], ['eggplant', 'bakłażan', 'B2'], ['artichoke', 'karczoch', 'B2'],
    ['turnip', 'rzepa', 'B2'], ['parsnip', 'pasternak', 'B2'], ['brussels sprout', 'brukselka', 'B2'],
    ['chickpea', 'ciecierzyca', 'B2'], ['lentil', 'soczewica', 'B2'], ['kale', 'jarmuż', 'B2'],
  ],
  jedzenie: [
    ['bread', 'chleb', 'A1'], ['butter', 'masło', 'A1'], ['cheese', 'ser', 'A1'],
    ['egg', 'jajko', 'A1'], ['milk', 'mleko', 'A1'], ['meat', 'mięso', 'A1'],
    ['fish', 'ryba', 'A1'], ['rice', 'ryż', 'A1'], ['soup', 'zupa', 'A1'],
    ['sugar', 'cukier', 'A1'], ['salt', 'sól', 'A1'], ['breakfast', 'śniadanie', 'A1'],
    ['lunch', 'obiad / lunch', 'A1'], ['dinner', 'kolacja / obiadokolacja', 'A1'],
    ['sandwich', 'kanapka', 'A2'], ['salad', 'sałatka', 'A2'], ['pasta', 'makaron', 'A2'],
    ['chicken', 'kurczak', 'A2'], ['sausage', 'kiełbasa', 'A2'], ['ham', 'szynka', 'A2'],
    ['flour', 'mąka', 'A2'], ['oil', 'olej', 'A2'], ['honey', 'miód', 'A2'],
    ['jam', 'dżem', 'A2'], ['dessert', 'deser', 'A2'], ['snack', 'przekąska', 'A2'],
    ['pepper (spice)', 'pieprz', 'A2'], ['yoghurt', 'jogurt', 'A2'], ['cereal', 'płatki śniadaniowe', 'B1'],
    ['dough', 'ciasto (surowe)', 'B1'], ['crust', 'skórka (chleba)', 'B1'], ['broth', 'bulion', 'B1'],
    ['leftovers', 'resztki jedzenia', 'B1'], ['portion', 'porcja', 'B1'], ['appetite', 'apetyt', 'B1'],
    ['diet', 'dieta', 'B1'], ['nutrition', 'odżywianie', 'B1'], ['calorie', 'kaloria', 'B1'],
    ['seasoning', 'przyprawa', 'B1'], ['garnish', 'dekoracja potrawy', 'B2'],
    ['delicacy', 'przysmak', 'B2'], ['staple food', 'podstawowy produkt spożywczy', 'B2'],
    ['savoury', 'słony / wytrawny', 'B2'], ['bland', 'mdły w smaku', 'B2'],
    ['stale', 'nieświeży / czerstwy', 'B2'], ['rancid', 'zjełczały', 'B2'],
  ],
  napoje: [
    ['water', 'woda', 'A1'], ['juice', 'sok', 'A1'], ['tea', 'herbata', 'A1'],
    ['coffee', 'kawa', 'A1'], ['beer', 'piwo', 'A2'], ['wine', 'wino', 'A2'],
    ['soda', 'napój gazowany', 'A2'], ['lemonade', 'lemoniada', 'A2'], ['smoothie', 'smoothie', 'A2'],
    ['hot chocolate', 'gorąca czekolada', 'A2'], ['sparkling water', 'woda gazowana', 'B1'],
    ['still water', 'woda niegazowana', 'B1'], ['espresso', 'espresso', 'B1'],
    ['herbal tea', 'herbata ziołowa', 'B1'], ['cocktail', 'koktajl (alkoholowy)', 'B1'],
    ['champagne', 'szampan', 'B1'], ['whisky', 'whisky', 'B2'], ['brandy', 'brandy', 'B2'],
    ['liqueur', 'likier', 'B2'], ['non-alcoholic', 'bezalkoholowy', 'B2'],
  ],
  rodzina: [
    ['mother', 'matka', 'A1'], ['father', 'ojciec', 'A1'], ['sister', 'siostra', 'A1'],
    ['brother', 'brat', 'A1'], ['parents', 'rodzice', 'A1'], ['son', 'syn', 'A1'],
    ['daughter', 'córka', 'A1'], ['grandmother', 'babcia', 'A1'], ['grandfather', 'dziadek', 'A1'],
    ['family', 'rodzina', 'A1'], ['husband', 'mąż', 'A2'], ['wife', 'żona', 'A2'],
    ['aunt', 'ciotka', 'A2'], ['uncle', 'wujek', 'A2'], ['cousin', 'kuzyn / kuzynka', 'A2'],
    ['niece', 'siostrzenica / bratanica', 'B1'], ['nephew', 'siostrzeniec / bratanek', 'B1'],
    ['grandchild', 'wnuk / wnuczka', 'B1'], ['relative', 'krewny', 'B1'],
    ['sibling', 'rodzeństwo (jedna osoba)', 'B1'], ['stepmother', 'macocha', 'B1'],
    ['stepfather', 'ojczym', 'B1'], ['in-laws', 'teściowie', 'B2'],
    ['godparent', 'chrzestny / chrzestna', 'B2'], ['ancestor', 'przodek', 'B2'],
    ['descendant', 'potomek', 'B2'], ['twin', 'bliźniak', 'B2'],
    ['only child', 'jedynak', 'B2'], ['widow', 'wdowa', 'B2'], ['widower', 'wdowiec', 'B2'],
  ],
  cialo: [
    ['head', 'głowa', 'A1'], ['hand', 'ręka (dłoń)', 'A1'], ['arm', 'ramię', 'A1'],
    ['leg', 'noga', 'A1'], ['foot', 'stopa', 'A1'], ['eye', 'oko', 'A1'],
    ['ear', 'ucho', 'A1'], ['nose', 'nos', 'A1'], ['mouth', 'usta', 'A1'],
    ['hair', 'włosy', 'A1'], ['finger', 'palec (u ręki)', 'A2'], ['toe', 'palec (u stopy)', 'A2'],
    ['back', 'plecy', 'A2'], ['stomach', 'brzuch', 'A2'], ['knee', 'kolano', 'A2'],
    ['shoulder', 'ramię (bark)', 'A2'], ['neck', 'szyja', 'A2'], ['tooth', 'ząb', 'A2'],
    ['tongue', 'język', 'A2'], ['skin', 'skóra', 'A2'], ['chest', 'klatka piersiowa', 'B1'],
    ['elbow', 'łokieć', 'B1'], ['wrist', 'nadgarstek', 'B1'], ['ankle', 'kostka (u nogi)', 'B1'],
    ['heart', 'serce', 'B1'], ['lung', 'płuco', 'B1'], ['brain', 'mózg', 'B1'],
    ['bone', 'kość', 'B1'], ['muscle', 'mięsień', 'B1'], ['blood', 'krew', 'B1'],
    ['spine', 'kręgosłup', 'B2'], ['liver', 'wątroba', 'B2'], ['kidney', 'nerka', 'B2'],
    ['nerve', 'nerw', 'B2'], ['vein', 'żyła', 'B2'], ['eyebrow', 'brew', 'B2'],
    ['eyelash', 'rzęsa', 'B2'], ['jaw', 'szczęka', 'B2'], ['chin', 'podbródek', 'B2'],
    ['forehead', 'czoło', 'B2'],
  ],
  zdrowie: [
    ['doctor', 'lekarz', 'A1'], ['hospital', 'szpital', 'A1'], ['pain', 'ból', 'A1'],
    ['medicine', 'lekarstwo', 'A2'], ['pharmacy', 'apteka', 'A2'], ['ill / sick', 'chory', 'A2'],
    ['headache', 'ból głowy', 'A2'], ['fever', 'gorączka', 'A2'], ['cold (illness)', 'przeziębienie', 'A2'],
    ['cough', 'kaszel', 'A2'], ['injury', 'kontuzja / uraz', 'A2'], ['nurse', 'pielęgniarka', 'A2'],
    ['appointment', 'wizyta (u lekarza)', 'B1'], ['prescription', 'recepta', 'B1'],
    ['symptom', 'objaw', 'B1'], ['treatment', 'leczenie', 'B1'], ['surgery', 'operacja', 'B1'],
    ['allergy', 'alergia', 'B1'], ['vaccine', 'szczepionka', 'B1'], ['bandage', 'bandaż', 'B1'],
    ['ambulance', 'karetka', 'B1'], ['injection', 'zastrzyk', 'B1'], ['x-ray', 'prześwietlenie rentgenowskie', 'B1'],
    ['diagnosis', 'diagnoza', 'B2'], ['recovery', 'powrót do zdrowia', 'B2'],
    ['chronic', 'przewlekły', 'B2'], ['infection', 'infekcja', 'B2'], ['immune system', 'układ odpornościowy', 'B2'],
    ['painkiller', 'środek przeciwbólowy', 'B2'], ['side effect', 'skutek uboczny', 'B2'],
  ],
  ubrania: [
    ['shirt', 'koszula', 'A1'], ['t-shirt', 'koszulka', 'A1'], ['trousers / pants', 'spodnie', 'A1'],
    ['dress', 'sukienka', 'A1'], ['skirt', 'spódnica', 'A1'], ['shoes', 'buty', 'A1'],
    ['jacket', 'kurtka', 'A1'], ['hat', 'czapka / kapelusz', 'A1'], ['socks', 'skarpetki', 'A1'],
    ['coat', 'płaszcz', 'A2'], ['sweater', 'sweter', 'A2'], ['jeans', 'dżinsy', 'A2'],
    ['scarf', 'szalik', 'A2'], ['gloves', 'rękawiczki', 'A2'], ['belt', 'pasek', 'A2'],
    ['boots', 'kozaki / botki', 'A2'], ['pyjamas', 'piżama', 'A2'], ['underwear', 'bielizna', 'A2'],
    ['suit', 'garnitur', 'B1'], ['tie', 'krawat', 'B1'], ['blouse', 'bluzka', 'B1'],
    ['shorts', 'krótkie spodenki', 'B1'], ['sandals', 'sandały', 'B1'], ['raincoat', 'płaszcz przeciwdeszczowy', 'B1'],
    ['zipper', 'zamek błyskawiczny', 'B1'], ['button', 'guzik', 'B1'], ['sleeve', 'rękaw', 'B1'],
    ['collar', 'kołnierz', 'B1'], ['hem', 'brzeg / obrębek ubrania', 'B2'],
    ['fabric', 'tkanina', 'B2'], ['outfit', 'strój', 'B2'], ['accessory', 'dodatek / akcesorium', 'B2'],
    ['cufflink', 'spinka do mankietu', 'B2'], ['wardrobe (clothes)', 'garderoba (ubrania)', 'B2'],
    ['tailor', 'krawiec', 'B2'], ['loose-fitting', 'luźny (o ubraniu)', 'B2'],
    ['tight-fitting', 'obcisły', 'B2'], ['second-hand', 'używany (z drugiej ręki)', 'B2'],
    ['formal wear', 'strój formalny', 'B2'],
  ],
  kolory: [
    ['red', 'czerwony', 'A1'], ['blue', 'niebieski', 'A1'], ['green', 'zielony', 'A1'],
    ['yellow', 'żółty', 'A1'], ['black', 'czarny', 'A1'], ['white', 'biały', 'A1'],
    ['orange (colour)', 'pomarańczowy', 'A1'], ['pink', 'różowy', 'A1'], ['purple', 'fioletowy', 'A2'],
    ['brown', 'brązowy', 'A2'], ['grey', 'szary', 'A2'], ['gold', 'złoty', 'B1'],
    ['silver', 'srebrny', 'B1'], ['turquoise', 'turkusowy', 'B2'],
  ],
  ksztalty: [
    ['circle', 'koło', 'A2'], ['square', 'kwadrat', 'A2'], ['triangle', 'trójkąt', 'A2'],
    ['rectangle', 'prostokąt', 'A2'], ['oval', 'owal', 'B1'], ['star (shape)', 'gwiazda (kształt)', 'B1'],
    ['heart (shape)', 'serce (kształt)', 'B1'], ['diamond (shape)', 'romb', 'B2'],
    ['cube', 'sześcian', 'B2'], ['cylinder', 'walec', 'B2'],
  ],
  liczby: [
    ['one', 'jeden', 'A1'], ['two', 'dwa', 'A1'], ['three', 'trzy', 'A1'],
    ['four', 'cztery', 'A1'], ['five', 'pięć', 'A1'], ['six', 'sześć', 'A1'],
    ['seven', 'siedem', 'A1'], ['eight', 'osiem', 'A1'], ['nine', 'dziewięć', 'A1'],
    ['ten', 'dziesięć', 'A1'], ['eleven', 'jedenaście', 'A1'], ['twelve', 'dwanaście', 'A1'],
    ['twenty', 'dwadzieścia', 'A1'], ['thirty', 'trzydzieści', 'A2'], ['forty', 'czterdzieści', 'A2'],
    ['fifty', 'pięćdziesiąt', 'A2'], ['hundred', 'sto', 'A2'], ['thousand', 'tysiąc', 'A2'],
    ['million', 'milion', 'A2'], ['first', 'pierwszy', 'A2'], ['second', 'drugi', 'A2'],
    ['third', 'trzeci', 'A2'], ['half', 'połowa', 'A2'], ['quarter', 'ćwierć / kwadrans', 'B1'],
    ['dozen', 'tuzin', 'B1'], ['double', 'podwójny', 'B1'], ['pair', 'para', 'B1'],
    ['zero', 'zero', 'A1'], ['odd number', 'liczba nieparzysta', 'B2'], ['even number', 'liczba parzysta', 'B2'],
    ['percentage', 'procent', 'B1'], ['fraction', 'ułamek', 'B2'], ['sum', 'suma', 'B1'],
    ['average', 'średnia', 'B1'], ['billion', 'miliard', 'B2'],
  ],
  czas: [
    ['Monday', 'poniedziałek', 'A1'], ['Tuesday', 'wtorek', 'A1'], ['Wednesday', 'środa', 'A1'],
    ['Thursday', 'czwartek', 'A1'], ['Friday', 'piątek', 'A1'], ['Saturday', 'sobota', 'A1'],
    ['Sunday', 'niedziela', 'A1'], ['January', 'styczeń', 'A2'], ['February', 'luty', 'A2'],
    ['March', 'marzec', 'A2'], ['April', 'kwiecień', 'A2'], ['May', 'maj', 'A2'],
    ['June', 'czerwiec', 'A2'], ['July', 'lipiec', 'A2'], ['August', 'sierpień', 'A2'],
    ['September', 'wrzesień', 'A2'], ['October', 'październik', 'A2'], ['November', 'listopad', 'A2'],
    ['December', 'grudzień', 'A2'], ['morning', 'rano', 'A1'], ['afternoon', 'popołudnie', 'A1'],
    ['evening', 'wieczór', 'A1'], ['night', 'noc', 'A1'], ['today', 'dzisiaj', 'A1'],
    ['tomorrow', 'jutro', 'A1'], ['yesterday', 'wczoraj', 'A1'], ['week', 'tydzień', 'A1'],
    ['month', 'miesiąc', 'A1'], ['year', 'rok', 'A1'], ['spring', 'wiosna', 'A2'],
  ],
  pogoda: [
    ['sun', 'słońce', 'A1'], ['rain', 'deszcz', 'A1'], ['snow', 'śnieg', 'A1'],
    ['wind', 'wiatr', 'A1'], ['cloud', 'chmura', 'A1'], ['hot', 'gorąco', 'A1'],
    ['cold (weather)', 'zimno', 'A1'], ['warm', 'ciepło', 'A1'], ['storm', 'burza', 'A2'],
    ['fog', 'mgła', 'A2'], ['ice', 'lód', 'A2'], ['temperature', 'temperatura', 'A2'],
    ['forecast', 'prognoza pogody', 'A2'], ['sunny', 'słoneczny', 'A2'], ['cloudy', 'pochmurny', 'A2'],
    ['rainy', 'deszczowy', 'A2'], ['windy', 'wietrzny', 'A2'], ['humidity', 'wilgotność', 'B1'],
    ['thunder', 'grzmot', 'B1'], ['lightning', 'błyskawica', 'B1'], ['hail', 'grad', 'B1'],
    ['drizzle', 'mżawka', 'B2'], ['frost', 'mróz', 'B1'], ['heatwave', 'fala upałów', 'B2'],
    ['blizzard', 'zamieć śnieżna', 'B2'],
  ],
  zwierzeta: [
    ['dog', 'pies', 'A1'], ['cat', 'kot', 'A1'], ['bird', 'ptak', 'A1'],
    ['fish (animal)', 'ryba (zwierzę)', 'A1'], ['horse', 'koń', 'A1'], ['cow', 'krowa', 'A1'],
    ['pig', 'świnia', 'A1'], ['sheep', 'owca', 'A1'], ['rabbit', 'królik', 'A1'],
    ['mouse', 'mysz', 'A1'], ['duck', 'kaczka', 'A2'], ['chicken (animal)', 'kura', 'A2'],
    ['lion', 'lew', 'A2'], ['tiger', 'tygrys', 'A2'], ['elephant', 'słoń', 'A2'],
    ['bear', 'niedźwiedź', 'A2'], ['wolf', 'wilk', 'A2'], ['fox', 'lis', 'A2'],
    ['deer', 'jeleń', 'A2'], ['monkey', 'małpa', 'A2'], ['snake', 'wąż', 'A2'],
    ['frog', 'żaba', 'A2'], ['bee', 'pszczoła', 'A2'], ['butterfly', 'motyl', 'A2'],
    ['spider', 'pająk', 'A2'], ['ant', 'mrówka', 'A2'], ['fly (insect)', 'mucha', 'A2'],
    ['mosquito', 'komar', 'B1'], ['owl', 'sowa', 'B1'], ['eagle', 'orzeł', 'B1'],
    ['dolphin', 'delfin', 'B1'], ['whale', 'wieloryb', 'B1'], ['shark', 'rekin', 'B1'],
    ['turtle', 'żółw', 'B1'], ['squirrel', 'wiewiórka', 'B1'], ['hedgehog', 'jeż', 'B1'],
    ['goat', 'koza', 'B1'], ['donkey', 'osioł', 'B1'], ['crow', 'wrona', 'B1'],
    ['pigeon', 'gołąb', 'B1'], ['swan', 'łabędź', 'B1'], ['peacock', 'paw', 'B2'],
    ['giraffe', 'żyrafa', 'B1'], ['zebra', 'zebra', 'B1'], ['kangaroo', 'kangur', 'B1'],
    ['penguin', 'pingwin', 'B1'], ['crocodile', 'krokodyl', 'B1'], ['lizard', 'jaszczurka', 'B2'],
    ['snail', 'ślimak', 'B2'], ['worm', 'robak', 'B2'], ['wasp', 'osa', 'B2'],
    ['seal', 'foka', 'B2'], ['otter', 'wydra', 'B2'], ['beetle', 'chrząszcz', 'B2'],
    ['herd', 'stado (np. bydła)', 'B2'], ['flock', 'stado (np. ptaków)', 'B2'],
  ],
  przyroda: [
    ['tree', 'drzewo', 'A1'], ['flower', 'kwiat', 'A1'], ['grass', 'trawa', 'A1'],
    ['forest', 'las', 'A2'], ['mountain', 'góra', 'A2'], ['river', 'rzeka', 'A2'],
    ['lake', 'jezioro', 'A2'], ['sea', 'morze', 'A2'], ['beach', 'plaża', 'A2'],
    ['sky', 'niebo', 'A2'], ['star (sky)', 'gwiazda (na niebie)', 'A2'], ['moon', 'księżyc', 'A2'],
    ['stone', 'kamień', 'A2'], ['sand', 'piasek', 'A2'], ['leaf', 'liść', 'A2'],
    ['root', 'korzeń', 'B1'], ['branch', 'gałąź', 'B1'], ['seed', 'nasiono', 'B1'],
    ['soil', 'gleba', 'B1'], ['field', 'pole', 'B1'], ['hill', 'wzgórze', 'B1'],
    ['valley', 'dolina', 'B1'], ['island', 'wyspa', 'B1'], ['coast', 'wybrzeże', 'B1'],
    ['cliff', 'klif', 'B1'], ['wave', 'fala', 'B1'], ['desert', 'pustynia', 'B1'],
    ['jungle', 'dżungla', 'B2'], ['volcano', 'wulkan', 'B2'], ['ecosystem', 'ekosystem', 'B2'],
  ],
  transport: [
    ['car', 'samochód', 'A1'], ['bus', 'autobus', 'A1'], ['train', 'pociąg', 'A1'],
    ['bike', 'rower', 'A1'], ['plane', 'samolot', 'A1'], ['taxi', 'taksówka', 'A1'],
    ['boat', 'łódź', 'A2'], ['ship', 'statek', 'A2'], ['motorcycle', 'motocykl', 'A2'],
    ['subway / metro', 'metro', 'A2'], ['tram', 'tramwaj', 'A2'], ['ticket', 'bilet', 'A2'],
    ['station', 'stacja / dworzec', 'A2'], ['airport', 'lotnisko', 'A2'], ['driver', 'kierowca', 'A2'],
    ['road', 'droga', 'A2'], ['traffic', 'ruch uliczny', 'B1'], ['traffic light', 'sygnalizacja świetlna', 'B1'],
    ['highway / motorway', 'autostrada', 'B1'], ['fuel / petrol', 'paliwo', 'B1'],
    ['engine', 'silnik', 'B1'], ['wheel', 'koło', 'B1'], ['seatbelt', 'pas bezpieczeństwa', 'B1'],
    ['pedestrian', 'pieszy', 'B1'], ['crossing', 'przejście dla pieszych', 'B1'],
    ['traffic jam', 'korek uliczny', 'B1'], ['fare', 'opłata za przejazd', 'B2'],
    ['runway', 'pas startowy', 'B2'], ['vehicle', 'pojazd', 'B2'], ['commute', 'dojeżdżać do pracy', 'B2'],
  ],
  podroze: [
    ['trip', 'wycieczka', 'A2'], ['holiday / vacation', 'wakacje', 'A2'], ['passport', 'paszport', 'A2'],
    ['suitcase', 'walizka', 'A2'], ['hotel', 'hotel', 'A2'], ['map', 'mapa', 'A2'],
    ['tourist', 'turysta', 'A2'], ['luggage', 'bagaż', 'A2'], ['departure', 'odlot / odjazd', 'B1'],
    ['arrival', 'przylot / przyjazd', 'B1'], ['boarding pass', 'karta pokładowa', 'B1'],
    ['to book', 'rezerwować', 'B1'], ['accommodation', 'zakwaterowanie', 'B1'],
    ['delayed', 'opóźniony', 'B1'], ['customs', 'odprawa celna', 'B1'], ['itinerary', 'plan podróży', 'B2'],
    ['sightseeing', 'zwiedzanie', 'B1'], ['guidebook', 'przewodnik (książka)', 'B1'],
    ['souvenir', 'pamiątka', 'B1'], ['visa', 'wiza', 'B1'], ['border', 'granica', 'B1'],
    ['reservation', 'rezerwacja', 'B1'], ['currency exchange', 'kantor wymiany walut', 'B2'],
    ['backpacker', 'plecakowicz (podróżnik)', 'B2'], ['cruise', 'rejs wycieczkowy', 'B2'],
    ['resort', 'kurort', 'B2'], ['excursion', 'wycieczka (zorganizowana)', 'B2'],
    ['jet lag', 'zmęczenie po zmianie strefy czasowej', 'B2'], ['round trip', 'podróż w obie strony', 'B2'],
    ['layover', 'przesiadka', 'B2'],
  ],
  miasto: [
    ['city', 'miasto', 'A1'], ['street', 'ulica', 'A1'], ['shop / store', 'sklep', 'A1'],
    ['school', 'szkoła', 'A1'], ['park', 'park', 'A1'], ['bank', 'bank', 'A1'],
    ['restaurant', 'restauracja', 'A1'], ['hospital', 'szpital', 'A1'], ['bridge', 'most', 'A2'],
    ['square (place)', 'plac', 'A2'], ['library', 'biblioteka', 'A2'], ['museum', 'muzeum', 'A2'],
    ['church', 'kościół', 'A2'], ['office', 'biuro', 'A2'], ['building', 'budynek', 'A2'],
    ['post office', 'poczta', 'A2'], ['police station', 'komisariat policji', 'A2'],
    ['pharmacy', 'apteka', 'A2'], ['market', 'targ / rynek', 'A2'], ['neighbourhood', 'sąsiedztwo / dzielnica', 'B1'],
    ['pavement / sidewalk', 'chodnik', 'B1'], ['skyscraper', 'wieżowiec', 'B1'],
    ['suburb', 'przedmieście', 'B1'], ['downtown / city centre', 'centrum miasta', 'B1'],
    ['roundabout', 'rondo', 'B1'], ['statue', 'pomnik / posąg', 'B1'], ['fountain', 'fontanna', 'B1'],
    ['town hall', 'ratusz', 'B1'], ['pedestrian zone', 'strefa piesza', 'B2'],
    ['residential area', 'osiedle mieszkaniowe', 'B2'], ['infrastructure', 'infrastruktura', 'B2'],
    ['municipality', 'gmina / samorząd', 'B2'], ['landmark', 'charakterystyczny obiekt / zabytek', 'B2'],
  ],
  szkola: [
    ['book', 'książka', 'A1'], ['pen', 'długopis', 'A1'], ['pencil', 'ołówek', 'A1'],
    ['teacher', 'nauczyciel', 'A1'], ['student', 'uczeń / student', 'A1'], ['classroom', 'sala lekcyjna', 'A1'],
    ['lesson', 'lekcja', 'A1'], ['homework', 'praca domowa', 'A1'], ['exam / test', 'egzamin / test', 'A2'],
    ['question', 'pytanie', 'A2'], ['answer', 'odpowiedź', 'A2'], ['subject', 'przedmiot (szkolny)', 'A2'],
    ['grade / mark', 'ocena', 'A2'], ['university', 'uniwersytet', 'A2'], ['degree', 'stopień naukowy', 'B1'],
    ['lecture', 'wykład', 'B1'], ['scholarship', 'stypendium', 'B1'], ['curriculum', 'program nauczania', 'B1'],
    ['assignment', 'zadanie (do wykonania)', 'B1'], ['essay', 'wypracowanie / esej', 'B1'],
    ['graduate', 'absolwent', 'B1'], ['semester', 'semestr', 'B1'], ['timetable / schedule', 'plan zajęć', 'B1'],
    ['principal / headteacher', 'dyrektor szkoły', 'B1'], ['textbook', 'podręcznik', 'B1'],
    ['literacy', 'umiejętność czytania i pisania', 'B2'], ['tuition fee', 'czesne', 'B2'],
    ['plagiarism', 'plagiat', 'B2'], ['dissertation', 'praca dyplomowa', 'B2'],
    ['enrolment', 'zapis na studia / do szkoły', 'B2'],
  ],
  biznes: [
    ['job', 'praca (posada)', 'A1'], ['work', 'praca (czynność)', 'A1'], ['company', 'firma', 'A2'],
    ['manager', 'kierownik / menedżer', 'A2'], ['salary', 'pensja', 'A2'], ['meeting', 'spotkanie', 'A2'],
    ['customer / client', 'klient', 'A2'], ['boss', 'szef', 'A2'], ['colleague', 'współpracownik', 'A2'],
    ['office worker', 'pracownik biurowy', 'A2'], ['email', 'e-mail', 'A2'], ['contract', 'umowa', 'B1'],
    ['invoice', 'faktura', 'B1'], ['deadline', 'termin ostateczny', 'B1'], ['shareholder', 'akcjonariusz', 'B1'],
    ['to negotiate', 'negocjować', 'B1'], ['revenue', 'przychód', 'B1'], ['to outsource', 'zlecać na zewnątrz', 'B1'],
    ['liability', 'odpowiedzialność (prawna)', 'B2'], ['merger', 'fuzja', 'B2'],
    ['budget', 'budżet', 'B1'], ['profit', 'zysk', 'B1'], ['loss', 'strata', 'B1'],
    ['investment', 'inwestycja', 'B1'], ['stakeholder', 'interesariusz', 'B2'],
    ['supply chain', 'łańcuch dostaw', 'B2'], ['recruitment', 'rekrutacja', 'B2'],
    ['resignation', 'rezygnacja z pracy', 'B2'], ['promotion (job)', 'awans', 'B1'],
    ['strategy', 'strategia', 'B1'], ['market share', 'udział w rynku', 'B2'],
    ['turnover', 'obrót (finansowy)', 'B2'], ['subsidiary', 'spółka zależna', 'B2'],
    ['freelancer', 'freelancer / wolny strzelec', 'B1'], ['headquarters', 'siedziba główna firmy', 'B2'],
    ['entrepreneur', 'przedsiębiorca', 'B1'], ['startup', 'startup', 'B1'],
    ['workforce', 'siła robocza', 'B2'], ['overtime', 'nadgodziny', 'B1'],
  ],
  technologia: [
    ['computer', 'komputer', 'A1'], ['phone', 'telefon', 'A1'], ['internet', 'internet', 'A1'],
    ['screen', 'ekran', 'A2'], ['keyboard', 'klawiatura', 'A2'], ['mouse (device)', 'mysz (komputerowa)', 'A2'],
    ['password', 'hasło', 'A2'], ['website', 'strona internetowa', 'A2'], ['app / application', 'aplikacja', 'A2'],
    ['file', 'plik', 'A2'], ['email address', 'adres e-mail', 'A2'], ['battery', 'bateria / akumulator', 'A2'],
    ['charger', 'ładowarka', 'A2'], ['printer', 'drukarka', 'B1'], ['software', 'oprogramowanie', 'B1'],
    ['hardware', 'sprzęt komputerowy', 'B1'], ['network', 'sieć', 'B1'], ['server', 'serwer', 'B1'],
    ['database', 'baza danych', 'B1'], ['download', 'pobieranie', 'B1'], ['upload', 'wysyłanie (do sieci)', 'B1'],
    ['update', 'aktualizacja', 'B1'], ['bug (software)', 'błąd w programie', 'B1'],
    ['browser', 'przeglądarka internetowa', 'B1'], ['cloud storage', 'przechowywanie w chmurze', 'B2'],
    ['encryption', 'szyfrowanie', 'B2'], ['artificial intelligence', 'sztuczna inteligencja', 'B2'],
    ['algorithm', 'algorytm', 'B2'], ['firewall', 'zapora sieciowa', 'B2'],
    ['malware', 'złośliwe oprogramowanie', 'B2'], ['bandwidth', 'przepustowość łącza', 'B2'],
    ['user interface', 'interfejs użytkownika', 'B2'], ['backup', 'kopia zapasowa', 'B1'],
    ['glitch', 'usterka / drobny błąd', 'B2'],
  ],
  sport: [
    ['football / soccer', 'piłka nożna', 'A1'], ['basketball', 'koszykówka', 'A1'], ['tennis', 'tenis', 'A1'],
    ['swimming', 'pływanie', 'A1'], ['running', 'bieganie', 'A1'], ['team', 'drużyna', 'A2'],
    ['player', 'zawodnik', 'A2'], ['coach', 'trener', 'A2'], ['match / game', 'mecz', 'A2'],
    ['ball', 'piłka', 'A1'], ['goal', 'gol / bramka', 'A2'], ['stadium', 'stadion', 'A2'],
    ['gym', 'siłownia', 'A2'], ['exercise', 'ćwiczenie', 'A2'], ['championship', 'mistrzostwa', 'B1'],
    ['referee', 'sędzia (sportowy)', 'B1'], ['score', 'wynik (meczu)', 'B1'], ['victory', 'zwycięstwo', 'B1'],
    ['defeat', 'porażka', 'B1'], ['training', 'trening', 'B1'], ['cycling', 'kolarstwo / jazda na rowerze', 'B1'],
    ['athlete', 'sportowiec', 'B1'], ['medal', 'medal', 'B1'], ['tournament', 'turniej', 'B1'],
    ['opponent', 'przeciwnik', 'B1'], ['stretching', 'rozciąganie', 'B2'],
    ['endurance', 'wytrzymałość', 'B2'], ['penalty (sport)', 'rzut karny', 'B2'],
    ['spectator', 'widz (na wydarzeniu sportowym)', 'B2'], ['warm-up', 'rozgrzewka', 'B1'],
  ],
  uczucia: [
    ['happy', 'szczęśliwy', 'A1'], ['sad', 'smutny', 'A1'], ['angry', 'zły / wściekły', 'A1'],
    ['tired', 'zmęczony', 'A1'], ['afraid / scared', 'przestraszony', 'A2'], ['surprised', 'zaskoczony', 'A2'],
    ['excited', 'podekscytowany', 'A2'], ['nervous', 'zdenerwowany', 'A2'], ['bored', 'znudzony', 'A2'],
    ['worried', 'zmartwiony', 'A2'], ['proud', 'dumny', 'A2'], ['embarrassed', 'zawstydzony', 'B1'],
    ['jealous', 'zazdrosny', 'B1'], ['confused', 'zdezorientowany', 'B1'], ['relieved', 'odczuwający ulgę', 'B1'],
    ['disappointed', 'rozczarowany', 'B1'], ['grateful', 'wdzięczny', 'B1'], ['lonely', 'samotny', 'B1'],
    ['anxious', 'niespokojny / lękowy', 'B2'], ['overwhelmed', 'przytłoczony', 'B2'],
    ['content', 'zadowolony (spokojnie)', 'B2'], ['furious', 'wściekły (bardzo)', 'B2'],
    ['heartbroken', 'załamany po stracie', 'B2'], ['hopeful', 'pełen nadziei', 'B2'],
    ['indifferent', 'obojętny', 'B2'],
  ],
  charakter: [
    ['kind', 'uprzejmy / miły', 'A2'], ['friendly', 'przyjazny', 'A2'], ['funny', 'zabawny', 'A2'],
    ['honest', 'uczciwy', 'A2'], ['polite', 'grzeczny', 'A2'], ['shy', 'nieśmiały', 'A2'],
    ['brave', 'odważny', 'A2'], ['lazy', 'leniwy', 'A2'], ['patient', 'cierpliwy', 'B1'],
    ['generous', 'hojny', 'B1'], ['selfish', 'samolubny', 'B1'], ['confident', 'pewny siebie', 'B1'],
    ['curious', 'ciekawski', 'B1'], ['stubborn', 'uparty', 'B1'], ['reliable', 'niezawodny', 'B1'],
    ['ambitious', 'ambitny', 'B1'], ['modest', 'skromny', 'B1'], ['arrogant', 'arogancki', 'B2'],
    ['sincere', 'szczery', 'B2'], ['cautious', 'ostrożny', 'B2'], ['optimistic', 'optymistyczny', 'B1'],
    ['pessimistic', 'pesymistyczny', 'B1'], ['sociable', 'towarzyski', 'B1'], ['reserved', 'powściągliwy', 'B2'],
    ['determined', 'zdeterminowany', 'B2'],
  ],
  czasowniki: [
    ['to be', 'być', 'A1'], ['to have', 'mieć', 'A1'], ['to go', 'iść / jechać', 'A1'],
    ['to do', 'robić', 'A1'], ['to see', 'widzieć', 'A1'], ['to eat', 'jeść', 'A1'],
    ['to drink', 'pić', 'A1'], ['to sleep', 'spać', 'A1'], ['to speak / talk', 'mówić', 'A1'],
    ['to read', 'czytać', 'A1'], ['to write', 'pisać', 'A1'], ['to listen', 'słuchać', 'A1'],
    ['to watch', 'oglądać', 'A1'], ['to like', 'lubić', 'A1'], ['to want', 'chcieć', 'A1'],
    ['to need', 'potrzebować', 'A1'], ['to work', 'pracować', 'A1'], ['to play', 'grać / bawić się', 'A1'],
    ['to live', 'mieszkać / żyć', 'A1'], ['to buy', 'kupować', 'A1'], ['to sell', 'sprzedawać', 'A2'],
    ['to give', 'dawać', 'A1'], ['to take', 'brać', 'A1'], ['to make', 'robić / tworzyć', 'A1'],
    ['to think', 'myśleć', 'A1'], ['to know', 'wiedzieć / znać', 'A1'], ['to understand', 'rozumieć', 'A2'],
    ['to help', 'pomagać', 'A1'], ['to start / begin', 'zaczynać', 'A2'], ['to finish', 'kończyć', 'A2'],
    ['to open', 'otwierać', 'A1'], ['to close', 'zamykać', 'A1'], ['to find', 'znajdować', 'A2'],
    ['to lose', 'gubić / przegrywać', 'A2'], ['to wait', 'czekać', 'A2'], ['to travel', 'podróżować', 'A2'],
    ['to arrive', 'przybywać', 'A2'], ['to leave', 'wyjeżdżać / zostawiać', 'A2'],
    ['to remember', 'pamiętać', 'A2'], ['to forget', 'zapominać', 'A2'], ['to borrow', 'pożyczać (od kogoś)', 'A2'],
    ['to lend', 'pożyczać (komuś)', 'B1'], ['to decide', 'decydować', 'B1'], ['to allow', 'pozwalać', 'B1'],
    ['to suggest', 'sugerować', 'B1'], ['to explain', 'wyjaśniać', 'B1'], ['to improve', 'poprawiać / ulepszać', 'B1'],
    ['to avoid', 'unikać', 'B1'], ['to achieve', 'osiągać', 'B1'], ['to complain', 'skarżyć się', 'B1'],
    ['to persuade', 'przekonywać', 'B2'], ['to assume', 'zakładać (przypuszczać)', 'B2'],
    ['to acknowledge', 'przyznawać / uznawać', 'B2'], ['to consider', 'rozważać', 'B1'],
    ['to hesitate', 'wahać się', 'B2'], ['to accomplish', 'dokonywać / osiągać', 'B2'],
  ],
  przymiotniki: [
    ['big / large', 'duży', 'A1'], ['small', 'mały', 'A1'], ['tall', 'wysoki', 'A1'],
    ['short', 'niski / krótki', 'A1'], ['long', 'długi', 'A1'], ['fast', 'szybki', 'A1'],
    ['slow', 'wolny', 'A1'], ['old', 'stary', 'A1'], ['new', 'nowy', 'A1'],
    ['young', 'młody', 'A1'], ['good', 'dobry', 'A1'], ['bad', 'zły', 'A1'],
    ['hot', 'gorący', 'A1'], ['cold', 'zimny', 'A1'], ['easy', 'łatwy', 'A1'],
    ['difficult / hard', 'trudny', 'A1'], ['cheap', 'tani', 'A2'], ['expensive', 'drogi', 'A2'],
    ['clean', 'czysty', 'A2'], ['dirty', 'brudny', 'A2'], ['full', 'pełny', 'A2'],
    ['empty', 'pusty', 'A2'], ['heavy', 'ciężki', 'A2'], ['light (weight)', 'lekki', 'A2'],
    ['strong', 'silny', 'A2'], ['weak', 'słaby', 'A2'], ['loud', 'głośny', 'A2'],
    ['quiet', 'cichy', 'A2'], ['dangerous', 'niebezpieczny', 'B1'], ['safe', 'bezpieczny', 'B1'],
    ['important', 'ważny', 'B1'], ['interesting', 'interesujący', 'A2'], ['boring', 'nudny', 'A2'],
    ['comfortable', 'wygodny', 'B1'], ['convenient', 'dogodny / wygodny (praktycznie)', 'B2'],
    ['fragile', 'kruchy / delikatny', 'B2'], ['flexible', 'elastyczny', 'B2'],
    ['obvious', 'oczywisty', 'B2'], ['ridiculous', 'śmieszny (w złym sensie)', 'B2'],
    ['reasonable', 'rozsądny', 'B2'],
  ],
  zakupy: [
    ['money', 'pieniądze', 'A1'], ['price', 'cena', 'A1'], ['shop assistant', 'sprzedawca', 'A2'],
    ['receipt', 'paragon', 'A2'], ['cash', 'gotówka', 'A2'], ['credit card', 'karta kredytowa', 'A2'],
    ['discount', 'zniżka', 'A2'], ['sale', 'wyprzedaż', 'A2'], ['to pay', 'płacić', 'A1'],
    ['change (money)', 'reszta (pieniądze)', 'A2'],
    ['shopping cart / trolley', 'wózek sklepowy', 'A2'], ['refund', 'zwrot pieniędzy', 'B1'],
    ['warranty / guarantee', 'gwarancja', 'B1'], ['bargain', 'okazja cenowa', 'B1'],
    ['budget (personal)', 'budżet (osobisty)', 'B1'], ['loan', 'pożyczka', 'B1'],
    ['debt', 'dług', 'B1'], ['savings', 'oszczędności', 'B1'], ['currency', 'waluta', 'B1'],
    ['installment', 'rata', 'B2'], ['subscription', 'subskrypcja', 'B1'],
    ['consumer', 'konsument', 'B2'],
  ],
  hobby: [
    ['music', 'muzyka', 'A1'], ['film / movie', 'film', 'A1'], ['painting', 'malowanie / obraz', 'A2'],
    ['drawing', 'rysowanie', 'A2'], ['photography', 'fotografia', 'A2'], ['reading', 'czytanie', 'A1'],
    ['dancing', 'taniec', 'A2'], ['singing', 'śpiewanie', 'A2'], ['gardening', 'ogrodnictwo', 'B1'],
    ['collecting', 'kolekcjonowanie', 'B1'], ['fishing', 'wędkowanie', 'A2'], ['hiking', 'piesze wędrówki', 'B1'],
    ['knitting', 'robienie na drutach', 'B1'], ['board game', 'gra planszowa', 'A2'],
    ['puzzle', 'układanka / puzzle', 'A2'], ['instrument (musical)', 'instrument muzyczny', 'A2'],
    ['concert', 'koncert', 'A2'], ['exhibition', 'wystawa', 'B1'], ['craft', 'rękodzieło', 'B1'],
    ['leisure time', 'czas wolny', 'B1'],
  ],
};

function buildBuiltinWords() {
  const list = [];
  let counter = 0;
  Object.entries(WORDS_RAW).forEach(([topic, items]) => {
    items.forEach(([en, pl, level]) => {
      counter += 1;
      list.push({ id: `w${counter}`, en, pl, category: topic, level });
    });
  });
  return list;
}

export const BUILTIN_WORDS = buildBuiltinWords();
export const LEVELS = ['A1', 'A2', 'B1', 'B2'];
